export const links=[
  [  "Company",

"Home",
"Terms",
"Privacy",
"Cookies",
"Affiliate terms",
"Download app",
"Pricing",
"Affiliate",
"Press",
"DeskTime in your language"],
["Learn more",

"All resources",
"Employee monitoring guide",
"Online employee time clock",
"Best time tracking apps",
"DeskTime for business",
"DeskTime for freelancers",
"FAQ",
"Case studies",
"Webinars",
"Blog"],
["Integrations",

"All integrations",
"Trello",
"Basecamp",
"Jira",
"Asana",
"Outlook Calendar",
"Google Calendar"],
["Features",

"All features",
"Automatic time tracking",
"URL & App tracking",
"Screenshots",
"Project time tracking",
"Shift schedule",
"Offline time tracking",
"Absence calendar",
"Mobile app",
"Feature request"],
["Help center",

"Contact us",
"Schedule a call",
"Send us an e-mail",
"Request In-person training",
"Open chat",
"Phone support",

"+1 (315) 6365354",
"MON-FRI 9:00-22:00 EET",]

]